### ISSUE TITLE
No module named 'netnode'

### ISSUE THREAD

**Issue by vadimszzz** [P4nda0s/IDABeautify#1]
IDA 7.7 (64-bit)
Python 3.9.0
Windows 10

```
C:\Program Files\IDA Pro 7.7\scripts\beautify.py: No module named 'netnode'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.7\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.7/scripts/beautify.py", line 5, in <module>
    import netnode
ModuleNotFoundError: No module named 'netnode'
```

**Comment by vadimszzz** [comment]
Fixed "No module named 'netnode'" in #2

Now this happens:

```
C:\Program Files\IDA Pro 7.7\scripts\beautify.py: __init__() missing 1 required positional argument: 'nodeid'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.7\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.7/scripts/beautify.py", line 323, in <module>
    remover_address_manager.initialize()
  File "C:/Program Files/IDA Pro 7.7/scripts/beautify.py", line 96, in initialize
    self.node = netnode.Netnode("Beautify.RemoverAddressManager")
TypeError: __init__() missing 1 required positional argument: 'nodeid'
```

**Comment by vadimszzz** [comment]
```
$ del /s netnode.py
$ pip install ida-netnode
```

Still the same error:

```
C:\Program Files\IDA Pro 7.7\scripts\beautify.py: __init__() missing 1 required positional argument: 'nodeid'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.7\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.7/scripts/beautify.py", line 323, in <module>
    remover_address_manager.initialize()
  File "C:/Program Files/IDA Pro 7.7/scripts/beautify.py", line 96, in initialize
    self.node = netnode.Netnode("Beautify.RemoverAddressManager")
TypeError: __init__() missing 1 required positional argument: 'nodeid'
```
